## Convolution of two images


Convolution is a mathematical operation behind a lot of models (CNN, for instance). I want to mess around by convolving two images -- still wip.

In [15]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

In [10]:
import cv2
im = cv2.imread("circle.png")

<class 'numpy.ndarray'>


In [29]:
from skimage import data
from skimage.viewer import ImageViewer as view

In [30]:
print('image matrix size: ', im.shape)   # print the size of image
print ('\n First 5 columns and rows of the image matrix: \n', im[:5,:5]*255 )
view(im).show()              # plot the image

image matrix size:  (227, 222, 3)

 First 5 columns and rows of the image matrix: 
 [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


[]

In [31]:
len(im)

227

In [33]:
x = np.arange(227)

In [ ]:
convolved = np.convolve(x, im)